const themeButton=document.querySelector('#themeToggle');
function setTheme(theme){document.documentElement.dataset.theme=theme;themeButton.textContent=theme==='dark'?'☀ Yorug‘ rejim':'☾ Tungi rejim';themeButton.setAttribute('aria-label',theme==='dark'?'Yorug‘ rejimga o‘tish':'Tungi rejimga o‘tish');themeButton.setAttribute('aria-pressed',String(theme==='dark'));try{localStorage.setItem('savdo-theme',theme)}catch(e){}}
setTheme(document.documentElement.dataset.theme==='light'?'light':'dark');
themeButton.onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={learned:[],saved:[],review:[],scores:{}};try{const x=JSON.parse(localStorage.getItem('terminlab-v1'));if(x&&typeof x==='object'){for(const k of ['learned','saved','review'])if(Array.isArray(x[k]))state[k]=x[k].filter(id=>TERMS.some(t=>t.id===id));if(x.scores&&typeof x.scores==='object')state.scores=x.scores}}catch(e){}
let group='all',filter='all',activeMode='cards',currentId=null,questions=[],qi=0,answers=[],locked=false;
function save(){try{localStorage.setItem('terminlab-v1',JSON.stringify(state))}catch(e){}}
function toggle(k,id){const i=state[k].indexOf(id);if(i<0)state[k].push(id);else state[k].splice(i,1);save();render();openTerm(id)}
function selected(){return TERMS.filter(t=>group==='all'||t.group===group)}
function visible(){const q=$('#search').value.trim().toLocaleLowerCase();return TERMS.filter(t=>(q||group==='all'||t.group===group)&&(filter==='all'||state[filter].includes(t.id))&&(!q||[t.term,t.sub,t.definition,t.example,t.cat].join(' ').toLocaleLowerCase().includes(q)))}
function render(){const list=visible(),items=selected(),n=items.filter(t=>state.learned.includes(t.id)).length;$('#selectedTitle').textContent=group==='all'?'Barcha sohalar':GROUPS.find(g=>g.id===group).name;$('#progressText').textContent=`${n} / ${items.length} termin o‘rganildi · ${items.filter(t=>state.review.includes(t.id)).length} ta takrorlash uchun`;$('#progressFill').style.width=(n/items.length*100)+'%';$('#count').textContent=`${list.length} ta kartochka${$('#search').value.trim()?' · barcha sohalardagi qidiruv':''}`;
$('#groupgrid').innerHTML=GROUPS.map(g=>{const a=TERMS.filter(t=>t.group===g.id),n=a.filter(t=>state.learned.includes(t.id)).length;return `<button class="group-card ${group===g.id?'selected':''}" data-group="${g.id}" aria-pressed="${group===g.id}"><span class="group-icon">${esc(g.icon)}</span><h3>${esc(g.name)}</h3><p>${esc(g.description)}</p><small>${a.length} termin · ${n} o‘rganildi</small></button>`}).join('');document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>selectGroup(b.dataset.group));
$('#filters').innerHTML=[['all','Barchasi'],['learned','✓ O‘rgandim'],['review','↻ Takrorlayman'],['saved','☆ Saqlangan']].map(([id,name])=>`<button data-filter="${id}" class="${filter===id?'active':''}" aria-pressed="${filter===id}">${name}</button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});
$('#grid').innerHTML=list.length?list.map(t=>`<button class="card ${state.learned.includes(t.id)?'learned':''}" data-term="${t.id}"><span class="tag">${esc(t.cat)}</span>${state.saved.includes(t.id)?'<span class="saved-tag">★</span>':''}<h3>${esc(t.term)}</h3><p>${esc(t.sub)}</p><small>${state.review.includes(t.id)?'↻ Takrorlash uchun':state.learned.includes(t.id)?'✓ O‘rganildi':'Izoh va misolni ochish'}</small></button>`).join(''):'<p class="empty">Bu tanlovda kartochka topilmadi. Boshqa so‘z yoki holatni tanlang.</p>';document.querySelectorAll('[data-term]').forEach(b=>b.onclick=()=>openTerm(b.dataset.term));}
function selectGroup(id){group=id;filter='all';$('#search').value='';resetQuiz();render();$('.learning-head').scrollIntoView({behavior:'smooth',block:'start'})}
function openTerm(id){const t=TERMS.find(t=>t.id===id);if(!t)return;currentId=id;$('#detailbody').innerHTML=`<span class="tag">${esc(t.cat)}</span><h2 id="detail-title">${esc(t.term)}</h2><p>${esc(t.sub)}</p><div class="block"><b>Sodda tushuntirish</b><p>${esc(t.definition)}</p></div><div class="block example"><b>Hayotiy misol</b><p>${esc(t.example)}</p></div>${t.where&&!t.where.startsWith('Amaliy tekshiruv:')?`<div class="block"><b>O‘ylab ko‘ring</b><p>${esc(t.where)}</p></div>`:''}${t.confusion?`<div class="block"><b>Nima bilan chalkashtirmaslik kerak?</b><p>${esc(t.confusion)}</p></div>`:''}<b>Shu sohadagi boshqa tushunchalar</b><div class="related">${t.related.map(r=>{const x=TERMS.find(x=>x.id===r);return `<button class="secondary" data-related="${r}">${esc(x.term)}</button>`}).join('')}</div><div class="actions">${[['learned','O‘rgandim'],['review','Takrorlayman'],['saved','Saqlash']].map(([k,label])=>`<button class="${state[k].includes(id)?'primary':'secondary'}" data-mark="${k}" aria-pressed="${state[k].includes(id)}">${state[k].includes(id)?'✓ ':''}${label}</button>`).join('')}<button class="secondary" id="nextcard">Keyingi →</button></div>`;document.querySelectorAll('[data-mark]').forEach(b=>b.onclick=()=>toggle(b.dataset.mark,id));document.querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>openTerm(b.dataset.related));$('#nextcard').onclick=()=>{const l=visible(),i=l.findIndex(x=>x.id===id);if(l.length)openTerm(l[(i+1)%l.length].id)};if(!$('#detail').open)$('#detail').showModal()}
$('.close').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
function mode(m){activeMode=m;for(const s of ['cards','quiz'])$('#'+s).hidden=s!==m;document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.mode===m);b.setAttribute('aria-pressed',String(b.dataset.mode===m))})}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>mode(b.dataset.mode));$('#search').oninput=render;$('#start').onclick=()=>$('#disciplines').scrollIntoView({behavior:'smooth'});$('#allGroups').onclick=()=>selectGroup('all');
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function makeQuestions(g){const pool=TERMS.filter(t=>t.group===g);const cases=CASES[g].map(([q,name,explanation])=>{const t=pool.find(t=>t.term===name);return {q,t,explanation}});const defs=shuffle(pool.filter(t=>!cases.some(x=>x.t.id===t.id))).slice(0,8).map(t=>({q:`«${t.sub}» — qaysi terminning ma’nosi?`,t,explanation:t.definition}));return shuffle([...cases,...defs]).map(x=>({...x,options:shuffle([x.t,...shuffle(pool.filter(t=>t.id!==x.t.id)).slice(0,3)])}))}
function resetQuiz(){questions=[];qi=0;answers=[];renderQuiz()}
function startQuiz(){if(group==='all')return;questions=makeQuestions(group);qi=0;answers=[];renderQuiz()}
function renderQuiz(){const box=$('#quizbox');$('#quizDescription').textContent=group==='all'?'Har bir sohaning o‘z testi bor. Yuqoridan yo‘nalish tanlang.':`${GROUPS.find(g=>g.id===group).name} · 10 savol · izoh va hayotiy vaziyatlar`;if(group==='all'){box.innerHTML='<div class="quiz-intro"><h3>Bir sohani tanlang</h3><p>IT, ta’lim yoki boshqa yo‘nalishni tanlang. Test faqat shu sohadagi terminlardan tuziladi.</p><button class="primary" id="choose">Sohalarga qaytish</button></div>';$('#choose').onclick=()=>$('#disciplines').scrollIntoView({behavior:'smooth'});return}
if(!questions.length){box.innerHTML=`<div class="quiz-intro"><span class="tag">BILIM SINOVI</span><h3>10 savolda bilimingizni tekshiring</h3><p>8 ta ma’no savoli va 2 ta amaliy vaziyat. Har javobdan keyin tushuntirishni o‘qing. Savollar va javoblar tartibi har safar almashadi.</p>${state.scores[group]?`<p>Oxirgi natija: ${state.scores[group].score} / 10</p>`:''}<button class="primary" id="begin">Testni boshlash</button></div>`;$('#begin').onclick=startQuiz;return}
if(qi>=questions.length){const score=answers.filter(a=>a.correct).length;state.scores[group]={score,date:new Date().toISOString()};save();const mistakes=questions.filter((q,i)=>!answers[i].correct);box.innerHTML=`<span class="tag">TEST YAKUNLANDI</span><h3>${score} / ${questions.length} to‘g‘ri javob</h3><p>${mistakes.length?'Quyidagi tushunchalarni qayta ko‘rib chiqing. Ular takrorlash ro‘yxatiga qo‘shildi.':'Ajoyib! Shu sohadagi boshqa tushunchalarni ham o‘rganishda davom eting.'}</p>${mistakes.map(q=>`<div class="result-item"><b>${esc(q.t.term)}</b><p>${esc(q.t.sub)}</p><button class="secondary" data-mistake="${q.t.id}">Kartochkani o‘qish</button></div>`).join('')}<div class="actions"><button class="primary" id="again">Yangi test</button><button class="secondary" id="backCards">Kartochkalarga qaytish</button></div>`;document.querySelectorAll('[data-mistake]').forEach(b=>b.onclick=()=>openTerm(b.dataset.mistake));$('#again').onclick=startQuiz;$('#backCards').onclick=()=>mode('cards');return}
const q=questions[qi];locked=false;box.innerHTML=`<div class="meter"><div style="width:${qi/questions.length*100}%"></div></div><span class="tag">SAVOL ${qi+1} / ${questions.length}</span><h3>${esc(q.q)}</h3><div class="options">${q.options.map(t=>`<button class="option" data-answer="${t.id}">${esc(t.term)}</button>`).join('')}</div><div id="feedback" aria-live="polite"></div>`;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(locked)return;locked=true;const correct=b.dataset.answer===q.t.id;answers.push({correct});if(!correct&&!state.review.includes(q.t.id)){state.review.push(q.t.id);save();render()}document.querySelectorAll('[data-answer]').forEach(x=>{x.disabled=true;if(x.dataset.answer===q.t.id)x.classList.add('correct');else if(x===b)x.classList.add('wrong')});$('#feedback').innerHTML=`<div class="feedback"><b>${correct?'To‘g‘ri!':'To‘g‘ri javob: '+esc(q.t.term)}</b><p>${esc(q.explanation)}</p></div><button class="primary" id="nextq">${qi===questions.length-1?'Natijani ko‘rish':'Keyingi savol'}</button>`;$('#nextq').onclick=()=>{qi++;renderQuiz()}})}
$('#restart').onclick=()=>group==='all'?resetQuiz():startQuiz();render();resetQuiz();
