const CASES={
it:[['O‘qituvchi tizimga kirdi, ammo moliyaviy hisobotni ko‘rmasligi kerak. Qaysi tekshiruv mos?','Authorization','Kimlik tasdiqlanishi va amallarga vakolat alohida tekshiriladi.'],['Saytning tugma va ariza shakli qaysi qismga kiradi?','Frontend','Foydalanuvchi ishlatadigan ko‘rinish frontendga tegishli.']],
ai:[['Bir ariza ikki marta kelganda ikki band qilish yaratilmasligi kerak. Qaysi xususiyat kerak?','Idempotency','Takroriy so‘rov ortiqcha natija yaratmasligi nazorat qilinadi.'],['Agent noma’lum chegirmani aytmasligi va vakolatdan tashqariga chiqmasligi kerak. Nima yordam beradi?','Guardrails','Tasdiqlangan qoidalar va dasturiy tekshiruvlar chegarani saqlashga yordam beradi.']],
data:[['Reklama bilan savdo birga oshdi. Bu sababni isbotlamaydigan bog‘liqlik qanday ataladi?','Correlation','Birga o‘zgarish sababni isbotlamaydi; mavsum kabi boshqa omillar bo‘lishi mumkin.'],['Bir xil ismli ikki o‘quvchini bazada aniq ajratish uchun nima kerak?','Primary key','Har yozuvning noyob kaliti bo‘lishi kerak; ism takrorlanishi mumkin.']],
sales:[['Mijoz kechqurun qayta qo‘ng‘iroq qilishni so‘radi. Qaysi tushuncha mos?','Follow-up','Qayta aloqa sababi va vaqti qayd etiladi.'],['Mijoz CRM oldi. Unga bog‘liq ma’lumot ko‘chirish xizmatini taklif qilish nima?','Cross-sell','Asosiy xaridga bog‘liq boshqa xizmat taklif qilinmoqda.']],
marketing:[['1000 ko‘rsatilishda 20 havola bosildi. Qaysi ko‘rsatkich 2 foiz bo‘ladi?','CTR','20 ÷ 1000 × 100 = 2%. Bosish turi bir xil bo‘lishi kerak.'],['Arizalar arzon, ammo tasodifiy lidlar ko‘p. Bir lid xarajatini qaysi ko‘rsatkich ifodalaydi?','CPL','Past CPLning o‘zi sifatli mijoz yoki sotuvni kafolatlamaydi.']],
business:[['Hamma taklifni bir xodim tayyorlaydi va ishlar shu yerda navbat bo‘lib qoladi. Bu nima?','Bottleneck','Jarayonning umumiy tezligini cheklayotgan tor joy mavjud.'],['Sinovga kelmaganlar bilan ishlash ketma-ketligi yozib qo‘yildi. Bu nima?','SOP','Standart ish tartibi mas’ul va qadamlarni aniq ko‘rsatadi.']],
finance:[['100 ming savdodan 40 ming yalpi foyda qoldi. Savdoga nisbatan 40 foiz qanday ko‘rsatkich?','Margin','Marja savdo daromadiga nisbatan hisoblanadi; ustama tannarxga qaraydi.'],['CRM to‘lovlari bank tushumlari bilan tekshirilmoqda. Bu nima?','Reconciliation','Ikki manba solishtirilib tafovut sababi aniqlanadi.']],
education:[['Kursdan oldin o‘quvchi darajasini aniqlash uchun test berildi. Qaysi baholash?','Diagnostic assessment','Boshlang‘ich diagnostika mos guruh va yordamni belgilashga xizmat qiladi.'],['Termin ta’rifini kartochkaga qaramasdan aytib ko‘ryapsiz. Qaysi usul?','Active recall','Xotiradan javobni tiklash faol eslashdir.']],
logistics:[['Keyin kelgan yogurtning muddati tezroq tugaydi. Avval shuni chiqarish qaysi tamoyil?','FEFO','FEFO kelgan sana emas, yaroqlilik muddati bo‘yicha tanlaydi.'],['Yetkazish kechiksa sotuv to‘xtamasligi uchun qo‘shimcha mahsulot saqlandi. Bu nima?','Safety stock','Talab va yetkazish noaniqligi uchun xavfsizlik zaxirasi saqlanadi.']],
hr:[['Yangi xodim mahsulot, jamoa va CRM bilan tanishtirildi. Qaysi jarayon?','Onboarding','Onboarding ishga moslashish uchun yo‘riqnoma va yordamni ham qamraydi.'],['Excel mutaxassisi o‘z kasbini chuqurlashtirib Power Query o‘rganyapti. Bu nima?','Upskilling','Mavjud yo‘nalishda yangi ko‘nikma olinmoqda; bu boshqa kasbga o‘tish emas.']]
};
